### ISSUE TITLE
Create a function so that we can recreate the original graph but zoom in (change the scale)

### ISSUE THREAD

**Issue by selmatir** [selmatir/sds192-mp2#2]

**Comment by selmatir** [comment]
we are going to have to set multiple arguments that will vary

**Comment by selmatir** [comment]
Function that only changes the Y axis limit:

plotscale <- function(X) {
            ggplot(data=table2, aes(x=general_votes, y=total_money)) +
        geom_point(aes(colour=cand_party_affiliation, shape=ge_winner), size=2.5) +
        ggtitle("Number of Votes and Contributions in \nNew York General House Election") +
        xlab("Number of Votes (thousands)") +
        ylab("Amount of Contribution (millions of dollars)") +
        theme_economist() +
        scale_color_discrete(name = "party") +
        scale_shape_discrete(name = "election's outcome") +
        scale_color_manual(labels = c("DEM", "REP"), values = c("#0006CC", "#CC0000")) +
        scale_x_continuous(limits=c(0,220000), breaks=c(0,100000,200000), labels = c("0","100","200")) +
        scale_y_continuous(limits=c(0,X), breaks=c(0,250000,500000,750000,1000000), labels=c("0","0.25","0.5","0.75", "1")) +
        theme(plot.title = element_text(hjust = 0.5),
              legend.title = element_text(size = 11),
              legend.text = element_text(size = 9),
              legend.position = "right",
              axis.title = element_text(size = 11))
}

**Comment by edennisk** [comment]
This looks great! I added some new parameters so we can change the y-axis breaks and labels (we should keep the x-axis constant over both plots, though).

**Comment by selmatir** [comment]
perfect!
