### ISSUE TITLE
Should we compare a state where democrats are dominant and one where republicans are? (maybe texas and new york) Should we keep the california graph?

### ISSUE THREAD

**Issue by selmatir** [selmatir/sds192-mp2#3]

**Comment by edennisk** [comment]
I think there's plenty to say about each graph. Maybe a DEM concentrated state would be cool to compare to REP, so I like the NY/TX idea. I'm happy to leave CA out of the equation, just because the other data has trends that are more noticeable.

**Comment by selmatir** [comment]
Sounds good! we'll leave california out.

**Comment by edennisk** [comment]
Actually, it would be interesting to have two plots for just New York, because the data is pretty concentrated save for two outliers, so the next graph can zoom in a little but leave out some of the data points.

**Comment by selmatir** [comment]
It would indeed be more interesting
